ad: andorra
ae: uae
af: afghanistan
ag: antigua
ai: anguilla
al: albania
am: armenia
ao: angola
aq: antarctica
ar: argentina
arab: arab
as: american samoa
asean: asean
at: austria
au: australia
aw: aruba
ax: aland
az: azerbaijan
ba: bosnia
bb: barbados
bd: bangladesh
be: belgium
bf: burkina faso
bg: bulgaria
bh: bahrain
bi: burundi
bj: benin
bl: saint barthelemy
bm: bermuda
bn: brunei
bo: bolivia
bq: bonaire
br: brazil
bs: bahamas
bt: bhutan
bv: bouvet
bw: botswana
by: belarus
bz: belize
ca: canada
cc: cocos
cd: congo
cefta: central europe
cf: central africa
cg: republic of congo
ch: switzerland
ci: cote d'ivoire
ck: cook islands
cl: chile
cm: cameroon
cn: china
co: 'colombia'
cp: clipperton
cr: costa rica
cu: cuba
cv: cape verde
cw: curacao
cx: christmas island
cy: cyprus
cz: czech
de: germany
dg: diego garcia
dj: djibouti
dk: denmark
dm: dominica
do: dominican republic
dz: algeria
eac: east africa
ec: ecuador
ee: estonia
eg: egypt
eh: western sahara
er: eritrea
es: spain
es-ct: catalonia
es-ga: galicia
es-pv: basque
et: ethiopia
eu: european union
fi: finland
fj: fiji
fk: falkland islands
fm: micronesia
fo: faroe islands
fr: france
ga: gabon
gb: united kingdom
gb-eng: england
gb-nir: northern ireland
gb-sct: scotland
gb-wls: wales
gd: grenada
ge: georgia
gf: french guiana
gg: guernsey
gh: ghana
gi: gibraltar
gl: greenland
gm: gambia
gn: guinea
gp: guadeloupe
gq: equatorial guinea
gr: greece
gs: south georgia
gt: guatemala
gu: guam
gw: guinea-bissau
gy: guyana
hk: hong kong
hm: heard island
hn: honduras
hr: croatia
ht: haiti
hu: hungary
ic: canary islands
id: indonesia
ie: ireland
il: israel
im: isle of man
in: india
io: british indian ocean
iq: iraq
ir: iran
is: iceland
it: italy
je: jersey
jm: jamaica
jo: jordan
jp: japan
ke: kenya
kg: kyrgyzstan
kh: cambodia
ki: kiribati
km: comoros
kn: saint kitts
kp: north korea
kr: south korea
kw: kuwait
ky: cayman islands
kz: kazakhstan
la: laos
lb: lebanon
lc: saint lucia
li: liechtenstein
lk: sri lanka
lr: liberia
ls: lesotho
lt: lithuania
lu: luxembourg
lv: latvia
ly: libya
ma: morocco
mc: monaco
md: moldova
me: montenegro
mf: saint martin
mg: madagascar
mh: marshall islands
mk: north macedonia
ml: mali
mm: myanmar
mn: mongolia
mo: macau
mp: northern mariana islands
mq: martinique
mr: mauritania
ms: montserrat
mt: malta
mu: mauritius
mv: maldives
mw: malawi
mx: mexico
my: malaysia
mz: mozambique
na: namibia
nc: new caledonia
ne: niger
nf: norfolk island
ng: nigeria
ni: nicagua
nl: netherlands
'no': norway
np: nepal
nr: nauru
nu: niue
nz: new zealand
om: oman
pa: panama
pc: pitcairn
pe: peru
pf: french polynesia
pg: papua new guinea
ph: philippines
pk: pakistan
pl: poland
pm: saint pierre
pn: pitcairn
pr: puerto rico
ps: palestine
pt: portugal
pw: palau
py: paraguay
qa: qatar
re: reunion
ro: romania
rs: serbia
ru: russia
rw: rwanda
sa: saudi arabia
sb: solomon islands
sc: seychelles
sd: sudan
se: sweden
sg: singapore
sh: saint helena
sh-ac: ascension
sh-hl: helena
sh-ta: tristan
si: slovenia
sj: svalbard
sk: slovakia
sl: sierra leone
sm: san marino
sn: senegal
so: somalia
sr: suriname
ss: south sudan
st: sao tome
sv: el salvador
sx: sint maarten
sy: syria
sz: eswatini
tc: turks
td: chad
tf: french southern
tg: togo
th: thailand
tj: tajikistan
tk: tokelau
tl: timor-leste
tm: turkmenistan
tn: tunisia
to: tonga
tr: turkey
tt: trinidad
tv: tuvalu
tw: taiwan
tz: tanzania
ua: ukraine
ug: uganda
um: us minor islands
un: united nations
us: usa
uy: uruguay
uz: uzbekistan
va: vatican
vc: saint vincent
ve: venezuela
vg: british virgin islands
vi: us virgin islands
vn: vietnam
vu: vanuatu
wf: wallis
ws: samoa
xk: kosovo
xx: unknown
ye: yemen
yt: mayotte
za: south africa
zm: zambia
zw: zimbabwe
